### PR TITLE
Install socat package as a dependency

### PR DESCRIPTION
**Pull request by yrobla**
This is used for stopping the process, but it is
not present on the image, install the package.

### CODE REVIEW

**Comment by jmencak** [comment]
Thank you for the PR.

```
$ docker pull registry.svc.ci.openshift.org/openshift/origin-v4.0:base
base: Pulling from openshift/origin-v4.0
Digest: sha256:cbd0e2931e6ae8cbd1522cd7226cff89629c21a3652f6fd57d84f405d432c07a
Status: Image is up to date for registry.svc.ci.openshift.org/openshift/origin-v4.0:base
$ docker run -it --rm --entrypoint /bin/bash registry.svc.ci.openshift.org/openshift/origin-v4.0:base
$ which socat
/usr/bin/socat
```

`socat` is also present in the downstream image.  On which image are you missing `socat`?

**Comment by yrobla** [comment]
Looking at tuned pod, doing an inspect, i get: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:227ebafafff2f6c6a11c7380bbd3fa18fab7b04e2696a9734d7fe1acf7712783

**Comment by jmencak** [comment]
Interesting.  Given `socat` is not the base image for rhel 7.x or 8.x and in the image you provided: LGTM.

**Pull request merged**
