### PR TITLE
Bug 1739322: Fix plugin_sysctl for tuned 2.11

### PR DESCRIPTION
**Pull request by jmencak**
Tuned 2.11 prior to commit a8f2a830 doesn't handle sysctl plugin with '<' '>'
modifiers properly resulting in program traceback and malfunction (see Red Hat
BZ1739418 for detail).

This PR adds a patch to address the issue.

### CODE REVIEW

**Comment by jmencak** [comment]
The same fix worked for `4.2.0-0.nightly-2019-08-14-211610` and `tuned-2.11.0-5`, merging.

**Comment by derekwaynecarr** [comment]
why was this merged without explicit cherry pick approval?

**Comment by derekwaynecarr** [comment]
spoke with @jwforres , moving forward, this should have still done normal process.

**Comment by jmencak** [comment]
@derekwaynecarr, /cherrypick ended up with conflicts and I had to create a normal PR against the 4.1 branch. Since the move from RHEL7.6 to RHEL7.7 broke NTO's operand due to buggy tuned 2.11, this merge could only do good rather than harm.  I wanted to have a working operator + logging that depends on it in 4.1.12, but realize I should've asked architect's approval first though -- sorry about that.

**Comment by eparis** [comment]
@jmencak the problem is that you clicked the 'merge' button. Do not EVER click the merge button in release-* branches. If you have some emergency in a release-* branch and believe special handling is needed please get help in #warroom-release in slack reach out to Jessica, Derek, Alex, or myself. Do not use the merge button.

If this is done again you will lose write access to all repos.

**Comment by jmencak** [comment]
@eparis understood and appreciate the help on #warroom-op-pipeline about this issue!

**Pull request merged**
