### PR TITLE
Add more context into the README.md

### PR DESCRIPTION
**Pull request by jmencak**
Adding a little more into into README.md.  As a side effect, test CI/CD.

### CODE REVIEW

**Comment by jmencak** [comment]
/cc @sjug , need to test:
1) https://github.com/openshift/release/pull/2007 (cluster-node-tuned image is being created).
2) {/}lgtm from an approver is enough to trigger the process ^

Thanks.

**Comment by sjug** [comment]
@jmencak Do you have docs on how I would go about testing this?

**Pull request merged**
